import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import { DndProvider } from 'react-dnd';
import { TouchBackend } from 'react-dnd-touch-backend'
import { HTML5Backend } from 'react-dnd-html5-backend'

import { Board } from '../components/Board';
import { Rack } from '../components/Rack';
import { Emojis } from '../constants';

export default function MainGame() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Word</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        {/* <h1>Solitairagrams</h1> */}
        <h1>Cool Name Here</h1>
        <DndProvider backend={HTML5Backend}>
            {/* <CustomDragLayer /> */}
              <Board />
              {/* <Rack /> */}
        </DndProvider>

      </main>
      <footer className={styles.footer}>
        Made with {Emojis[Math.floor(Math.random() * (Emojis.length - 1))]} by Sahishnu
      </footer>

    </div>
  )
}
