import { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {isMobile} from 'react-device-detect';
import { DndProvider } from 'react-dnd';
import { TouchBackend } from 'react-dnd-touch-backend'
import { HTML5Backend } from 'react-dnd-html5-backend'

import { Board } from '../components/Board';
import { Header } from '../components/Header';
import { Emojis } from '../constants';

export default function MainGame() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Word Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <div></div>
        <div className={styles.game}>
          <Header />
          <DndProvider backend={isMobile ? TouchBackend : HTML5Backend}>
              {/* <CustomDragLayer /> */}
                <Board />
                {/* <Rack /> */}
          </DndProvider>
        </div>
        <footer className={styles.footer}>
          Made with {Emojis[Math.floor(Math.random() * (Emojis.length - 1))]} by Sahishnu
        </footer>
      </main>

    </div>
  )
}
